description: >
  Use preevy/up to deploy a multi-services preview environment that updates on every commit in the branch and exposes an HTTPS url for every service.

usage:
  version: 2.1

  orbs:
    preevy: livecycle/preevy@0.0.1
    aws-cli: circleci/aws-cli@3.1.5

  jobs:
    deploy_preview:
      environment:
        AWS_REGION: eu-west-1
      docker:
        - image: cimg/node:lts
      steps:
        - preevy/install
        - aws-cli/setup:
            role-arn: "arn:aws:iam::12345678:role/circleci"
            aws-region: AWS_REGION
        - preevy/init:
            profile_url: "s3://preevy-12345678?region=eu-west-1"
        - checkout
        - preevy/up:
            docker_compose_yaml_path: "./production/docker-compose.yaml"
  workflows:
    deploy_preview:
      jobs:
        - deploy_preview
